name: Generate OpenAPI Page
on:
  push:
    branches:
    - master
    paths:
    - openapi.yaml
    - openapi.yml
jobs:
  publish:
    name: Publish Page
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - name: Generate SwaggerUI
      uses: Legion2/swagger-ui-action@v1
      with:
        output: docs
        spec-file: openapi.yaml
    - name: Deploy to GitHub Pages
      uses: peaceiris/actions-gh-pages@v3
      with:
        github_token: ${{ secrets.GITHUB_TOKEN }}
        publish_dir: docs
